### ISSUE TITLE
Cannot disable scroll when on subpage

### ISSUE THREAD

**Issue by sydneyselch** [sydneyselch/trenches-demo#1]
- Trying to disable the scroll bar on the page behind my subpage so it stays on the subpage and does not allow you to scroll below and reach the page behind it. The page behind it will remain hidden as if it is not there. 

![screen shot 2015-11-03 at 12 40 18 pm](https://cloud.githubusercontent.com/assets/6373190/10916162/15e0839a-8228-11e5-8718-59178b1400f6.png) When you click on the first set of work shown above: A subpage appears 

![screen shot 2015-11-03 at 12 43 47 pm](https://cloud.githubusercontent.com/assets/6373190/10916256/975855f6-8228-11e5-8af5-daf6e12a96c2.png) 

This is working well and you are able to scroll within the container(blue border) which I intended.

![screen shot 2015-11-03 at 12 45 24 pm](https://cloud.githubusercontent.com/assets/6373190/10916301/ceabb886-8228-11e5-9e20-7430145e1b78.png) Though, when you get to the bottom of the container with your scroll bar... A second scroll bar appears and it starts scrolling within the body page that is below it. I want it so that it will stop at the bottom of the container and NOT show the services and other things below it. I can't figure out what to target to get the scroll bar to turn off on the background page.

My current code is: 
HTML:
< div class="lightbox" >
    < div class="container" >
                    (CONTENT)
    < /div >
< /div >

..there are not spaces in my code. It wasn't showing up without them

CSS:
.lightbox{
    position: absolute;
    top:0;
    left:0;
    width: 100%;
    height: 100vh;
    max-height: 100vh;
    overflow-y:auto;
    overflow-x: hidden;
    opacity: 0;
    background-color: white;
}

.lightbox:target {
    opacity: 1;
    z-index: 50;
}

.lightbox > .container{
     overflow: hidden;
    border:1px solid blue;
}

Another issue about it... 

You click on something in the work section, the subpage with work on it appears. When you click the x and exit the page it has bumped you all the way back to the top cover page. How do I get it to stay at the #work id when you close the subpage? 

@thomasjbradley @ccmadrid 

http://sydneyselch.github.io/trenches-demo/

**Comment by thomasjbradley** [comment]
Unfortunately that's something we'll have to wait to fix until Javascript time.
We'll make the Javascript change the `<html>` element to `overflow: hidden` when the lightbox is shown.
