### ISSUE TITLE
How to add .gitignore files

### ISSUE THREAD

**Issue by sydneyselch** [sydneyselch/trenches-demo#2]
How do I add the gitignore file correctly so that my github does not sync the site files?

I tried following along with what github said but was afraid to mess it up. 

I tried to add the gitignore file, then saw it will not recognize files that are already there and you need to remove the cached info. So I did git rm --cached. Not sure if I messed things up or not doing so. I see that I now have a gitignore file in my brackets but don't know what to do with it!!

Not really sure why it created the gitignore file and why there is certain type in it as I didn't tell it what to look for yet. Just CONFUSED. 

![screen shot 2015-12-21 at 10 38 34 pm](https://cloud.githubusercontent.com/assets/6373190/11947359/ae77ef72-a833-11e5-8537-d167a7f0e19f.png)
![screen shot 2015-12-21 at 10 38 27 pm](https://cloud.githubusercontent.com/assets/6373190/11947360/ae7b043c-a833-11e5-89e7-4db12bdf7fd5.png)

![screen shot 2015-12-21 at 10 30 01 pm](https://cloud.githubusercontent.com/assets/6373190/11947338/7e19f8c0-a833-11e5-8b6d-92283c506c91.png)
![screen shot 2015-12-21 at 10 34 06 pm](https://cloud.githubusercontent.com/assets/6373190/11947337/7e1717b8-a833-11e5-8118-92a517289309.png)

Help!!!! @thomasjbradley

**Comment by thomasjbradley** [comment]
1. Turn off Jekyll in terminal.
2. Delete the _site folder completely.
3. Go to the GitHub app and commit all the changes of the _site deletion.
4. Add just "_site" into the .gitignore file.
5. Commit that change.

Then all should be good.
